name: CI
on: 
  push:
    branches:
      - main
concurrency: production

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # prepare semver
      - name: Minor version for each merge
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      - name: echo part
        run: |
          echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"


      # build    
      # - name: Set Node.js 18.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18.x

      # - name: Run install
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: install

      # - name: Run tsc
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: tsc
      # - name: Run build
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build:backend --config ../../app-config.yaml 


      # do semver
      - name: Minor version for each merge
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      # publish docker image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }} 

      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.taggerFinal.outputs.new_tag }}"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerFinal.outputs.tag }}"
      - name: echo part
        run: |
          echo "The version increment was: ${{ steps.taggerFinal.outputs.part }}"
      
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #       context: .
      #       file: packages/backend/Dockerfile
      #       push: true
      #       tags: lazno/backstage:${{ steps.taggerFinal.outputs.new_tag }}
